### ISSUE TITLE
Firmware version question

### ISSUE THREAD

**Issue by itbabu** [RegioHelden/innovazammad#4]
Hello,
we are thinking to move to innovaphone.
in the read readme you say:
_Currently innovazammad uses innovaphone's v11 SOAP API (see innovaphone/pbx.wsdl). Older PBX versions might not work._

What firmware version are you using? v11 or v12?
we asked if it was possible to install your extension in the pbx and they (the dealer) said we should downgrade the firmware version to v11.

In the innovaphone wiki i cannot find a newer version of v11 soap api
https://www.innovaphone.com/wsdl/pbx11_00.wsdl
http://wiki.innovaphone.com/index.php?title=Reference:SOAP_API

Marco

**Comment by lociii** [comment]
We're running 11r2 sr33 on an IP810.
However the innovazammad system is running on a separate machine.

What's their reasoning to ask for a forced downgrade?

**Comment by itbabu** [comment]
Hello,
 the dealer says that innovazammad is not compatible with the last firmware version (v12 / v13).
Could you explain the innovazammad machine setup?  we thought we could install the software directly in the pbx
Marco

**Comment by saz** [comment]
Technically, innovazammad is written in Go. It's possible to set it up on the linux appliance of Innovaphone PBXs.
We've made the decision to run it on a separate machine to avoid any issues with upgrades on the Innovaphone system (we've not tested this setup at all).

Innovazammad can be run on any linux distro. It just needs to be able to communicate with the Innovaphone PBX API and zammad.

The changes between v11 and v12 are not breaking the API endpoints innovazammad is using.

I've also updated the README to reflect that (also added newer zammad versions).

The SOAP API is described here: http://wiki.innovaphone.com/index.php?title=Reference:SOAP_API

**Comment by itbabu** [comment]
ok thanks, we'll use a similar setup: 
innovazammad system running on a machine and a virtual pbx in a different machine.
We are still waiting for a test number for doing the first tests with the integration.
i'll keep you updated.
Cheers
Marco

**Comment by regiohelden-dev** [comment]
I'll close this topic for now. Feel free to open a new one if you're running into issues with your installation.
