### ISSUE TITLE
Run multiple instances simultaneously

### ISSUE THREAD

**Issue by wucherpfennig** [RegioHelden/innovazammad#5]
Hi there

we are testing to integrate your nice piece of software with our Innovaphone but we face one big question: are we able to run multiple instances of this package simultaneously?

Best regards
wucherpfennig

**Comment by costela** [comment]
I have only done some light testing in this direction but it _seems_ to work. The main unknown is the PBX: its open APIs are somewhat flaky and there are few guarantees, particularly because we use a long-polling endpoint to receive events, which is - of course - less than optimal.

What's your use-case for multiple instances?

**Comment by wucherpfennig** [comment]
ok, we will see ;-) fingers crossed

well we have multiple (currently two) zammad instances but one pbx which means we need to split the calls somehow

**Comment by wucherpfennig** [comment]
Just out of curiousity: if we are getting the following error. Is this a configuration mistake or something with the pbx?

![image](https://user-images.githubusercontent.com/3634653/79570911-9167e900-80ba-11ea-95a6-7583976927a3.png)

// edit

we are currently running on:
* pbx: Version 13r1 sr11 IP411
* zammad: 3.3

**Comment by costela** [comment]
@wucherpfennig your config seems to be using the wrong format for the PBX' URL: it should be a URL with scheme, so `http://172.16.0.5` or `https://172.16.0.5`. Should probably make this clearer in the README... :sweat_smile:

**Comment by wucherpfennig** [comment]
well that helped ;-) but now I am receiving an 401 error. Do you know how to setup the soap user as well ?

![image](https://user-images.githubusercontent.com/3634653/79584642-f6c5d500-80ce-11ea-9a6f-7d45cbd427b5.png)

**Comment by costela** [comment]
@wucherpfennig you might be trying to use a "normal" user (i.e. a telephony user). You actually have to use an [administrative user](https://wiki.innovaphone.com/index.php?title=Reference10:General/Admin#Additional_Administrator_Accounts). I _think_ it's ok if this user is only a "viewer", but I'm not sure and unfortunately I can't test right now. You might have to test with an admin user as well to be sure.

**Comment by wucherpfennig** [comment]
Dear @costela 

Thank you for your help. It works! 

Just one last question: with the option `filterongroup` is it possible to filter on *multiple* groups? if yes how to do so (by comma separated names i guess)?

**Comment by costela** [comment]
@wucherpfennig unfortunately that's not currently supported (see [here](https://github.com/RegioHelden/innovazammad/blob/21c93718833f35229c3ad46d492eeaaddb1408dc/innovaphone/innovaphone.go#L257) for the current implementation). That being said, I believe this shouldn't be a problem: you can create a group just for filtering and add multiple groups as members, achieving basically the same objective.

**Comment by wucherpfennig** [comment]
@costela thank you again for your help. It runs smoothly now. 

The only thing we have to check now. is why the number / contact in zammad is not that "intelligent" ;-)
